### ISSUE TITLE
Etc: 디폴트 프로필 수정, 추가 document 작성

### ISSUE THREAD

**Issue by msung99** [msung99/Gatsby-Starter-Haon#12]
## 무엇이 필요한가요? (What do you want?)

- 서비스 소개를 더 개성있게 표현하도록 도큐먼트를 수정한다.

---

## Todo

- [X] 디폴트 리드미 파일 날짜 변경
- [X] static 파일 기본 이미지 중앙 정렬
- [X] Readme.md Desktop 이미지 추가
